---

- name: Ensure stirling_pdf network is created in Docker
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ stirling_pdf_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"


- name: Ensure stirling_pdf path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0700"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
  with_items:
    - {path: "{{ stirling_pdf_base_path }}", when: true}
    - {path: "{{ stirling_pdf_config_path }}", when: true}

- name: Ensure stirling_pdf data, log and training data paths exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
  with_items:
    - {path: "{{ stirling_pdf_data_path }}", when: true}
    - {path: "{{ stirling_pdf_training_data_path }}", when: true}
    - {path: "{{ stirling_pdf_logs_path }}", when: true}
    - {path: "{{ stirling_pdf_data_path }}/config", when: true}
    - {path: "{{ stirling_pdf_data_path }}/customFiles", when: true}
    - {path: "{{ stirling_pdf_data_path }}/pipeline", when: true}
    - {path: "{{ stirling_pdf_pipeline_default_webui_configs_path }}", when: true}


- name: Ensure stirling_pdf traefik labels are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ stirling_pdf_config_path }}/labels"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
    mode: "0640"

- name: Ensure stirling_pdf configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ stirling_pdf_config_path }}/env"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
    mode: "0640"

- name: Ensure stirling_pdf extra config is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/extra_config.j2"
    dest: "{{ stirling_pdf_data_path }}/config/settings.yml"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
    mode: "0660"

- name: Ensure stirling_pdf container image is pulled
  community.docker.docker_image:
    name: "{{ stirling_pdf_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure stirling_pdf.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/stirling_pdf.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ stirling_pdf_identifier }}.service"
    mode: "0644"
