---

- name: Validate and install stirling_pdf if enabled
  when: stirling_pdf_enabled | bool
  tags:
    - setup-all
    - setup-stirling-pdf
    - install-all
    - install-stirling-pdf
  block:
    - name: Include Stirling PDF config validation tasks
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Include Stirling PDF install tasks
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall stirling_pdf if not enabled
  when: not stirling_pdf_enabled | bool
  tags:
    - setup-all
    - setup-stirling-pdf
  block:
    - name: Include Stirling PDF uninstall tasks
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
